name: ios

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cbindgen and cargo-lipo
      run: cargo install cbindgen cargo-lipo
    - name: Install llvm
      run: brew install llvm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
