name: ios

on:
  workflow_run:
    workflows: ["macos"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ios targets
      run: rustup target add aarch64-apple-ios x86_64-apple-ios
    - name: Install cbindgen and cargo-lipo
      run: cargo install cbindgen cargo-lipo
    - name: Install llvm
      run: brew install llvm
    - name: Install xbuild
      run: cargo install xbuild
    - name: Check xbuild status
      run: x doctor
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose